name: year_month_picker
description: "A Flutter package that enables users to select a year and month via a dialog or bottom sheet interface."
version: 1.0.0
repository: https://github.com/PhiLongDo/year_month_picker
issue_tracker: https://github.com/PhiLongDo/year_month_picker/issues

environment:
  sdk: ^3.5.3
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
